### ISSUE TITLE
How to Open this flutter project in android studio

### ISSUE THREAD

**Issue by fisforfaheem** [ShehriyarShariq/FlutterCalculator#1]
I have been trying to understand  but am unable to do please help.

**Comment by ShehriyarShariq** [comment]
Glad to see you here. I'll update the README later with basic instructions on how to open this in Android Studio.

**Comment by fisforfaheem** [comment]
Please alsoemail me if possible fisforfaheem@gmail.com

**Comment by fisforfaheem** [comment]
For the past we weeks i am trying very hard to make it simple and easier to find a github project and work upon it but for flutter it never works well and got problems i tried everything

**Comment by marciokuroki** [comment]
Hi, @fisforfaheem I don't know if you have solved the open flutter project problem. But I found this link, maybe help you in this issue!

https://medium.com/codespace69/how-to-import-existing-flutter-project-in-android-studio-aa9d9e5c77b

**Comment by fisforfaheem** [comment]
I will let you know,
