### ISSUE TITLE
Still no tutorial on opening it on android studio (DART FILES and etc flutter project) not the 

### ISSUE THREAD

**Issue by fisforfaheem** [ShehriyarShariq/FlutterCalculator#2]
Still no tutorial on opening it on android studio (DART FILES and etc flutter project) not the auto created android project..

**Comment by fisforfaheem** [comment]
suppose this is the porject:
https://flutterawesome.com/a-flutter-app-based-on-the-design-of-the-to-do-app/
how should i open it ...)(fluuter prohject_

**Comment by fisforfaheem** [comment]
https://github.com/LiveLikeCounter/Flutter-Todolist

**Comment by ShehriyarShariq** [comment]
Faheem, have you cloned the project? If yes then just goto android studio and redirect to the directory where you have cloned it. Android studio should automatically recognize the folder as a flutter project.

**Comment by ShehriyarShariq** [comment]
Also, I would recommend that you should work on VSCode rather than Android Studio. It is much easier to set up and it's light weight.
